site_name: Kubernetes Fundamentals
pages:
  - Home: "index.md"
  - Provisioning VMs with Vagrant: "2_kube-cluster-vagrant.md"
  - Setup Kubernetes Cluster: "3_install_kubernetes.md"
  - Configuring Cluster: "4_configs.md"
  - Launching Pods: "5_deploying_pods.md"
  - Creating Deployments: "6_kubernetes_deployment.md"
  - Service Endpoints: "7_exposing_app_with_service.md"
  - Rollouts and Rollbacks: "8_rollouts-and-rollbacks.md"
  - Using Configmaps and Secrets: "9_using_configmaps_and_secrets.md"
  - Auto Scaling Capacity with HPA : "10_kubernetes_autoscaling.md"
  - Troubleshooting: "12_troubleshooting.md"
  - Mini Project: "11_deploying_sample_app.md"
  - Troubleshooting Tips: "12_troubleshooting.md"
docs_dir: chapters
theme: readthedocs
