site_name: Ultimate Kubernetes Bootcamp
pages:
  - Home: "index.md"
  - Setup:
     - Using minikube to setup single node environment: "minikube.md"
     - Provisioning VMs with Vagrant: "2_kube_cluster_vagrant.md"
     - Setup Kubernetes Cluster: "3_install_kubernetes.md"
     - Kuberentes Visualizer : "kube_visualizer.md"
  - Bootcamp:
     - Quickstart: "run_and_publish_image.md"
     - Launching Pods: "5_deploying_pods.md"
     - Configuring Cluster: "4_configs.md"
     - Creating Deployments: "6_kubernetes_deployment.md"
     - Service Endpoints: "7_exposing_app_with_service.md"
     - Deployment Strategies: "9_deployement_strategies.md"
     - Persistent Volume Setup: "persistent-volumes.md"
     - Using Configmaps and Secrets: "9_using_configmaps_and_secrets.md"
     - Auto Scaling Capacity with HPA : "10_kubernetes_autoscaling.md"
     - Mini Project: "11_deploying_sample_app.md"
  - Additional Topics:
     - Production grade setup with Kubespray: "cluster_setup_kubespray.md"
     - Troubleshooting Tips: "12_troubleshooting.md"
  - Securing Kubernetes:
     - Authentication and Authorization: "configuring_authentication_and_authorization.md"
#     - Setting up Pod Security Policy: "pod_security.md"
docs_dir: chapters
theme: readthedocs
plugins:
    - search
