site_name: Ultimate Kubernetes Bootcamp
pages:
  - Home: "index.md"
  - Setup:
     - Using minikube to setup single node environment: "minikube.md"
     - Provisioning VMs with Vagrant: "2_kube_cluster_vagrant.md"
     - Setup Kubernetes Cluster: "3_install_kubernetes.md"
     - Kuberentes Visualizer : "kube_visualizer.md"
  - Bootcamp:
     - Launching Pods: "5-vote-deploying_pods.md"
     - Making application highly available: "replication.md"
     - Publishing appliaction and Service Discovery: "7-vote-exposing_app_with_service.md"
     - Defining Update Strategy: "6-vote-kubernetes_deployment.md"
     - Managing Configurations and Secrets: "9-vote-configmaps_and_secrets.md"
     - Making Data Persist: "vote-persistent-volumes.md"
     - Mini Project: "11_deploying_sample_app.md"
     - Building Deployment Strategies: "vote-deployement_strategies.md"
     - Auto Scaling Capacity with HPA : "10_kubernetes_autoscaling.md"
     - Application Routing with Ingress Controllers : "ingress.md"
     - Creating Replicated Cluster Setup for Redis: "13_redis_statefulset.md"
     - Access Control with Network Policies: "network_policies.md"
     - Ingress Controllers: "ingress.md"
  - Being Edited:
     - Troubleshooting Tips: "12_troubleshooting.md"
  - Additional Topics:
     - Production grade setup with Kubespray: "cluster_setup_kubespray.md"
     - Troubleshooting Tips: "12_troubleshooting.md"
  - Securing Kubernetes:
     - Authentication and Authorization: "configuring_authentication_and_authorization.md"
#     - Setting up Pod Security Policy: "pod_security.md"
docs_dir: chapters
theme: readthedocs
plugins:
    - search
