site_name: Ultimate Kubernetes Bootcamp
pages:
  - Home: "index.md"
  - Setup:
     - Using minikube to setup single node environment: "minikube.md" 
     - Provisioning VMs with Vagrant: "2_kube-cluster-vagrant.md"
     - Setup Kubernetes Cluster: "3_install_kubernetes.md"
  - Quick Dive:
     - Configuring Cluster: "4_configs.md"
     - Launching Pods: "5_deploying_pods.md"
     - Creating Deployments: "6_kubernetes_deployment.md"
     - Service Endpoints: "7_exposing_app_with_service.md"
     - Rollouts and Rollbacks: "8_rollouts-and-rollbacks.md"
     - Using Configmaps and Secrets: "9_using_configmaps_and_secrets.md"
     - Auto Scaling Capacity with HPA : "10_kubernetes_autoscaling.md"
     - Mini Project: "11_deploying_sample_app.md"
  - Additional Topics:
     - Production grade setup with Kubespray: "cluster-setup-kubespray.md"
     - Troubleshooting Tips: "12_troubleshooting.md"
  - Securing Kubernetes:
     - Authentication and Authorization: "configuring-authentication-and-authorization.md"
     - Setting up Pod Security Policy: "pod_security.md"
docs_dir: chapters
theme: readthedocs
plugins:
    - search
