apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: carts
  namespace: instavote
  labels:
    app: carts
    env: dev
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: carts
          image: schoolofdevops/carts
          imagePullPolicy: Always
          
